sudo: required  
dist: trusty 

language: node_js
node_js:
  - stable
  - "6.5.0"

before_script:
  - python -m SimpleHTTPServer &
  - sleep 2

cache:
  directories:
    - node_modules

addons:
  sauce_connect:
    username: "Maartenconnect"
    access_key: "4fd375a2-a635-42fb-860e-346e4d6691a6"